### ISSUE TITLE
How to port this project to Linux distros?

### ISSUE THREAD

**Issue by scc-tw** [alankuo04/rv32I-emulator#3]
Hi there,

I'm interested in your repository.
How can I compile this program on my Linux laptop?

**Comment by alankuo04** [comment]
> Hi there,
> 
> I'm interested in your repository. How can I compile this program on my Linux laptop?

Hi @25077667 , there are the steps for compiling Qt project on linux,

First, installing the qmake.
```
sudo apt-get install qt5-default qt5-doc-html qt5-qmake qt5-doc qt5-image-formats-plugins
```
Then, cloning the rv32I-emulator repository.
```
git clone https://github.com/alankuo04/rv32I-emulator.git
```

Next, change the directory to src, and run qmake.
```
cd src/
qmake
```

The Makefile will generate by qmake, then run make to compile the project.
```
make
```

Finally, you get the executable file RV32I_emulator, and you can run it on your pc.
```
./RV32I_emulator
```
However, some icons are in wrong position, maybe I will fix it in the future.
